load("//:tools.bzl", "neversql_binary")

neversql_binary("data-manager-example.cpp")
neversql_binary("database-string-pk.example.cpp")
neversql_binary("ReadWAL.cpp")
neversql_binary("store-shakespeare.cpp")

neversql_binary("hex-dump.cpp")